name: vcf_dart
description: A VCF (VCard) file parser from scratch. It contains support for VCard 2.x-4.x (except the AGENT type).
version: 1.0.0
repository: https://github.com/frknkrc44/vcf_dart

environment:
  sdk: ^3.1.0

dependencies:
  # No dependency required for this library.

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
